name: release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['addons/**']

jobs:
  release:
    runs-on: [self-hosted, arma-tools]
    steps:

    - name: Checkout files
      uses: actions/checkout@v3

    - name: Build addons
      uses: team-gsri/actions-build-addon@0.1.0
      with:
        source: ./addons/gsri_zeusmanager
        target: ./
        prefix: 'fr\gsri\zeusmanager'
        includes: '*.paa;*.sqf;*.jpg;*.xml'

    - name: Upload pbo files
      uses: actions/upload-artifact@v3
      with:
        name: addons
        path: ./*.pbo

    - name: Create Github release
      uses: arwynfr/actions-conventional-versioning@0.1.0
      with:
        pattern: $(Convert-Path *.pbo)
