name: release

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['addons/**']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Lint sources
      uses: jokoho48/sqflint@master
      with:
        args: --exit e --directory addons

  build:
    needs: lint
    runs-on: [self-hosted, arma-tools]
    steps:

    - name: Checkout files
      uses: actions/checkout@v2

    - name: Build addons
      uses: team-gsri/actions-build-addon@0.0.2
      with:
        source: 'addons/gsri_zeusmanager'
        target: 'addons'
        prefix: 'fr\gsri\zeusmanager'
        includes: '*.paa;*.sqf;*.jpg;*.xml'

    - name: Upload pbo files
      uses: actions/upload-artifact@v2
      with:
        name: addons
        path: addons/*.pbo
      
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download pbo files
      uses: actions/download-artifact@v2
      with:
        name: addons
        path: ./addons

    - name: Create Github release
      uses: arwynfr/actions-conventional-versioning@0.1.0
      with:
        pattern: ./addons/*.pbo
